# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3eeaceb900c17f594a7fb3c60651b617"
application_url = "https://breakfast-concerning-aggressive-subjective.trycloudflare.com"
embedded = true
name = "remix-test-app"
handle = "remix-test-app-31"

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://breakfast-concerning-aggressive-subjective.trycloudflare.com/auth/callback",
  "https://breakfast-concerning-aggressive-subjective.trycloudflare.com/auth/shopify/callback",
  "https://breakfast-concerning-aggressive-subjective.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "apple-store007.myshopify.com"
automatically_update_urls_on_dev = true
